add tests
yiisoft/yii2-symfonymailer pull request #3
Opened 2021-12-24 10:06 UTC by Krakozaber

2021-12-24 10:20 UTC, terabytesoftw commented
Hi, you have tested if with the version `5.4` which is the default in https://github.com/symfony/mailer  works, since it supports `PHP 7`.

Thks,

2021-12-24 10:25 UTC, Krakozaber commented
Sorry, I used symfony/mailer version 6.0.0 right away

2021-12-24 10:25 UTC, Krakozaber commented
> Hi, you tested if with the version `5.4` which is the default in https://github.com/symfony/mailer works, since it supports `PHP > 7.2.5`.
> 
> Thks,

Sorry, I used symfony/mailer version 6.0.0 right away

2021-12-24 11:14 UTC, samdark requested changes

2021-12-24 11:14 UTC, samdark commented on .github/FUNDING.yml
> +"
```suggestion
```

2021-12-24 11:14 UTC, samdark commented on .github/ISSUE_TEMPLATE.md
> +| SwiftMailer version     |
```suggestion
| Yii Symfony Mailer version |
| Symfony mailer version     |
```

2021-12-24 11:14 UTC, samdark commented on README.md
> +> Note: Version 2.0 of this extensions uses Symfonymailer, which requires PHP 8.
```suggestion
> Note: Version 2.0 of this extension uses Symfonymailer, which requires PHP 8.
```

2021-12-24 11:14 UTC, samdark commented on .github/workflows/build.yml
> +              if: matrix.php == '7.1'
If we use PHP 8.0+ only, these conditions aren't needed.

2021-12-24 11:14 UTC, samdark commented on composer.json
>          "symfony/mailer": "~6.0.0"
That's a big question if we want PHP 8 only.

2021-12-24 11:14 UTC, samdark commented on composer.json
>          "symfony/mailer": "~6.0.0"
For a new package it may be alright...

2021-12-24 11:35 UTC, Krakozaber commented on composer.json
>          "symfony/mailer": "~6.0.0"
"symfony/mailer": "~6.0.0" use "php": ">=8.0.2". If someone can test on earlier versions it will be cool.

2021-12-24 11:37 UTC, Krakozaber commented on .github/workflows/build.yml
> +              if: matrix.php == '7.1'
removed

2021-12-24 11:37 UTC, samdark commented on composer.json
>          "symfony/mailer": "~6.0.0"
Let's merge it with 6.0.0 first.

2021-12-24 11:38 UTC, merged

2021-12-29 03:22 UTC, Krakozaber commented
@terabytesoftw #6 php7.4 support